// -----------------------------------------------------------------
// <copyright file="KnownSpell.cs" company="2Dudes">
// Copyright (c) 2018 2Dudes. All rights reserved.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------

namespace OpenTibia.Server.Contracts.Enumerations
{
    public enum KnownSpell : byte
    {
        AnimateDead,
        Antidote,
        AntidoteRune,
        Berserk,
        CancelInvisibility,
        Challenge,
        Chameleon,
        ConjureArrow,
        ConjureBolt,
        ConvinceCreature,
        CreatureIllusion,
        Desintegrate,
        DestroyField,
        EnchantStaff,
        EnergyBeam,
        Energybomb,
        EnergyField,
        EnergyStrike,
        EnergyWall,
        EnergyWave,
        Envenom,
        Explosion,
        ExplosiveArrow,
        FindPerson,
        Fireball,
        Firebomb,
        FireField,
        FireWall,
        FireWave,
        FlameStrike,
        Food,
        ForceStrike,
        GreatEnergyBeam,
        GreatFireball,
        GreatLight,
        Haste,
        HealFriend,
        HeavyMagicMissile,
        IntenseHealing,
        IntenseHealingRune,
        Invisible,
        Levitate,
        Light,
        LightHealing,
        LightMagicMissile,
        MagicRope,
        MagicShield,
        MagicWall,
        MassHealing,
        Paralyze,
        PoisonBomb,
        PoisonedArrow,
        PoisonField,
        PoisonStorm,
        PoisonWall,
        PowerBolt,
        Soulfire,
        StrongHaste,
        SuddenDeath,
        SummonCreature,
        UltimateExplosion,
        UltimateHealing,
        UltimateHealingRune,
        UltimateLight,
        UndeadLegion,
        WildGrowth,
    }
}
